### ISSUE TITLE
Return Route, not RouteInterface in Phalcon\Mvc\Router\Group::add

### ISSUE THREAD

**Issue by fabian-mcfly** [fossapps/PhpStorm-Phalcon-Autocomplete#3]
The PHPDoc for \Phalcon\Mvc\Router\Group::add states, that add() on a group would return an instance of Phalcon\Mvc\RouteInterface but it really returns an instance of Phalcon\Mvc\Route

This results in PHPStorm not finding the convert() method on a group object.

**Comment by cyberhck** [comment]
Hi @fabsn182 sorry, I was out for New Year and Christmas and didn't even notice there was an issue here.
This repository really leverages data from phalcon's build, and I didn't update it, I'm hoping to update to a new version soon. Thanks for the report.

I'll keep this issue open for now and I'll verify if new version will fix it. Thanks :slightly_smiling_face: 
I just had a look in phalcon's ide stubs. Looks like it's generating wrong stubs. If you want, you could create a new issue in https://github.com/phalcon/ide-stubs I'll wait for your response, if not I'll create a issue tomorrow.

**Comment by cyberhck** [comment]
generation is fixed now: https://github.com/phalcon/ide-stubs/issues/4 closing.
