### ISSUE TITLE
Update for Phalcon 3.3.*

### ISSUE THREAD

**Issue by JABirchall** [fossapps/PhpStorm-Phalcon-Autocomplete#4]
Is this repo maintained any more? I used this plugin over the stubs because its easier. But hasnt been updated in ages.

**Comment by cyberhck** [comment]
Sorry about that, I missed the last one, but not to worry, according to a issue in stubs repository, there's no change in 3.3.2 or something, I will try to give a update as soon as I can. I really need to setup a automated way of doing this :D maybe will do that :)

**Comment by JABirchall** [comment]
Phalcon 3.4 is coming out soon https://github.com/phalcon/cphalcon/pull/13362

**Comment by sergeyklay** [comment]
We're released
- Phalcon 3.4.0: https://github.com/phalcon/cphalcon/releases/tag/v3.4.0 
- IDE Stubs 3.4.0: https://github.com/phalcon/ide-stubs/releases/tag/v3.4.0

**Comment by sergeyklay** [comment]
I propose to close this issue. This is implemented: https://github.com/fossapps/PhpStorm-Phalcon-Autocomplete/releases If there are bugs, we can follow up in separate issues :)

**Comment by cyberhck** [comment]
ahh, I didn't, let's see if my auto release feature is working :slightly_smiling_face:
